### ISSUE TITLE
Support for Availability Groups - jobs could fail when Readable-Secondary is set to Read-Only

### ISSUE THREAD

**Issue by DaveDustin** [DanielLoth/SQLServerJobRunner#7]
In [JobRunner.AddAgentJob](https://github.com/DanielLoth/SQLServerJobRunner/blob/main/src/JobRunner/JobRunner/Stored%20Procedures/AddAgentJob.sql) the [msdb.dbo.sp_add_jobstep](https://github.com/DanielLoth/SQLServerJobRunner/blob/9987cc1b02bcfc11384ccb75797c311569df3e83/src/JobRunner/JobRunner/Stored%20Procedures/AddAgentJob.sql#L99) assigns the @database_name value to the target database for the job.

If this job were running on a secondary node where the Readable-Secondary configuration is set to Read-Only instead of All the job will fail because it cannot connect to the database to execute the step.

**Comment by DanielLoth** [comment]
Fixed. Thanks for pointing this out.
